version: "3"
services:
  web:
    build: .
    restart: always
    environment:
      - FLASK_ENV
      - POSTGRES_URL
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./data/database:/var/lib/postgresql/data
