name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Check code style with black
        uses: lgeiger/black-action@master
        with:
          args: . --check

      - name: Lint with flake8
        run: |
          pip install --upgrade pip
          pip install --upgrade flake8
          # Fail on syntax errors and undefined names
          flake8 . --count --select=E9,F63,F7,F82,F84 --show-source --statistics
          # Treat all other errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
