name: ci

on: [push, pull_request]

jobs:
  run:
    name: Codecov
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout master
      uses: actions/checkout@v2
      
    - name: Set up python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.x
                  
    - name: Generate coverage report
      run: |
        pip install -U pytest pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-umbrella
        flags: unittests
        fail_ci_if_error: true
