name: ci

on: [push, pull_request]

jobs:
  run:
    name: Codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]
    
    steps: 
    - name: Checkout master
      uses: actions/checkout@v2
      
    - name: Set up python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: ${{ matrix.python-version }}
                  
    - name: Generate coverage report
      run: |
        pip install -U pytest pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-umbrella
        flags: unittests
        fail_ci_if_error: true
